version: "3.8"
services:
  app:
    #image: php:8.0-fpm-alpine3.13
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - TZ=Asia/Tokyo
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ../lara-sample:/work
    working_dir: /work
    command: php artisan serve --host=0.0.0.0