version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile.apache
      args:
        - TZ=Asia/Tokyo
        - PHP_MODE=production
    ports:
      - 9001:80
    env_file:
      - ./.env
    volumes:
      - ../lara-sample:/var/www/html
    working_dir: /var/www/html
